**This notebook, contains examples of linear algebra operations done with the NumPy package.**

Please, follow the lecture 2 to see the examples used here

In [5]:
import numpy as np # as usual, importing the numpy package

In [6]:
# define a column vector
x = np.array([[1], [5], [3]]) # Notice the use of the squared brackets. Each bracket contains 1 element
x # This lines prints out x.

array([[1],
       [5],
       [3]])

In [7]:
x.shape # The command shape, will tell you the dimensions of the array. x is a 2D array.
        # In the lecture 2, we use this kind of dimensions

(3, 1)

In [8]:
# Now, check what happens if I define a new x, say xp, using one squared bracket only.
xp = np.array([1,3,5])
xp

array([1, 3, 5])

In [9]:
# Let's find the dimensions of xp. Notice this is a 1D array. It's like a list of numbers.
xp.shape

(3,)

In [10]:
# define a row vector
y = np.array([[1, 2, 3]]) # Notice here how the squared bracked contains 3 numbers
y

array([[1, 2, 3]])

In [11]:
y.shape

(1, 3)

In [12]:
# extract elements from a vector
# Note; python indexes at 0. So, 0=1
print(x[0,0]) # Notice what's happening here: it's picking the element of x that occupies the first row, first column

1


In [13]:
print(x[1,0])

5


In [14]:
#and 1=2, etc.
print(y[0,1])

2


In [15]:
# vector addition and subtraction
x = np.array([[1], [3]]) # Both x and y are column vectors
y = np.array([[2], [2]])
print(f'Vector addition:\n {x + y}')
print(f'Vector subtraction:\n {x - y}')

Vector addition:
 [[3]
 [5]]
Vector subtraction:
 [[-1]
 [ 1]]


In [65]:
# Tis code trial

a = np.array([[1],[5]])
b = np.array([[7],[2]])
vector_add = a + b
print(vector_add)

[[8]
 [7]]


In [16]:
# take the transpose of a vector. .T computes the transpose.
x.T

array([[1, 3]])

In [17]:
# Hadamard Product (aka, element-wise multiplication)
x * y

array([[2],
       [6]])

In [18]:
x.T.shape, y.shape

((1, 2), (2, 1))

In [19]:
# dot product
np.dot(x.T, y) # Notice the transpose

array([[8]])

In [20]:
np.dot(x.T,y).item() # .item(). Why? What's that? Check the output with and without .item()

8

In [21]:
# inner product (note the need for both to be row vectors)
print(np.inner(x.flatten().T, y.flatten())) # .flatten()? what's that about. This takes a while...

# np.inner, and np.outer, work for 1D arrays. But our arrays, x and y, are 2D. What to do then? You flatten them:
# flattening an array makes it 1D. So now you can use np.inner (and np.outer). If you don't believe me that flatten
# makes a 2D array a 1D, simple do x.flatten().shape and compare it with x.shape

8


In [22]:
print(np.inner(x.flatten(), y.flatten())) # No need for transpose here

8


In [23]:
x.flatten().shape, x.shape, x.flatten().T.shape

((2,), (2, 1), (2,))

In [24]:
# outer product
print(np.outer(x.flatten(), y.flatten())) # Notice: outer also works with 1D vectors. Problem is,
                                          # where's the transpose? It actually does not need it.

[[2 2]
 [6 6]]


In [25]:
# outer product
print(np.outer(x, y)) # It also works if you don't flatten it

[[2 2]
 [6 6]]


In [26]:
# multiply by a constant
3*x, x

(array([[3],
        [9]]),
 array([[1],
        [3]]))

In [27]:
# NumPy solutions to Practice
x = np.array([[0], [1]])
y = np.array([[1], [2]])
z = np.array([[3], [1]])

x + y + z

array([[4],
       [4]])

In [67]:
#x - 2*y.T #even if python gives you something, it might not be correct!
trial = x - 2*y.T
print(trial)

[[0 2]
 [4 6]]


In [29]:
np.outer(x.flatten(), z.flatten().T)

array([[0, 0],
       [3, 1]])

**np.outter()**

For the syntax of np.dot()*italicized text*, check this link:
https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [30]:
np.dot(z.T, y)

array([[5]])

In [31]:
np.dot(z.T, y).item()

5

In [32]:
y * x

array([[0],
       [2]])

In [33]:
4*np.dot(z.T, x) + np.dot((x - y).T, z * x)

array([[3]])

In [34]:
(4*np.dot(z.T, x) + np.dot((x - y).T, z * x)).item()

3

In [35]:
# create a matrix
X = np.array([[3, 16, 0],
              [4, 14, 15],
              [4, 16, 6]])
X

array([[ 3, 16,  0],
       [ 4, 14, 15],
       [ 4, 16,  6]])

In [36]:
X.shape

(3, 3)

In [37]:
# extract columns, rows, elements from the matrix
# remember that python indexes starting at 0
X[:,0] #the first column

array([3, 4, 4])

In [38]:
X[1,:] #the second row

array([ 4, 14, 15])

In [39]:
print(X[2,1]) #the element in the third row, second column

16


In [40]:
# transpose a matrix
X.T

array([[ 3,  4,  4],
       [16, 14, 16],
       [ 0, 15,  6]])

In [41]:
# Matrix Hadamard Product
X = np.array([[1, 0],
              [2, 1]])
Z = np.array([[1, 3],
              [2, 3]])
X*Z

array([[1, 0],
       [4, 3]])

In [42]:
#multiply or add constants
2*X

array([[2, 0],
       [4, 2]])

In [43]:
X + 2

array([[3, 2],
       [4, 3]])

**np.matmul()**

For a syntax of matrix multiplication, np.matmul(), check this link https://numpy.org/doc/2.1/reference/generated/numpy.matmul.html

In [44]:
# Matrix Multiplication (dot product)
np.matmul(X, Z)

array([[1, 3],
       [4, 9]])

In [45]:
# another way, using .dot() (a bit cleaner, perhaps)
X.dot(Z)

array([[1, 3],
       [4, 9]])

In [46]:
# Other rules
(np.matmul(X, Z).T == np.matmul(Z.T, X.T)).all() # This creates a Boolean array. .all() checks if all the
                                                 # elements of the array are true

np.True_

In [47]:
np.matmul(X, Z).T == np.matmul(Z.T, X.T) # Printing out so we can see what's happening in the cell above

array([[ True,  True],
       [ True,  True]])

In [48]:
np.matmul(X, Z)

array([[1, 3],
       [4, 9]])

In [49]:
np.matmul(Z, X)

array([[7, 3],
       [8, 3]])

**np.diag()**

https://numpy.org/devdocs/reference/generated/numpy.diag.html

In [50]:
# Diagonal of the matrix (note, NumPy gives you a row vector by default)
np.diag(X), X

(array([1, 1]),
 array([[1, 0],
        [2, 1]]))

In [51]:
# Diagonal of non-square matrix
Y = np.array([[2, 4, 6],
              [5, 3, 1]])
np.diag(Y)

array([2, 3])

In [52]:
# Trace of the matrix
np.trace(X).item(), X

(2,
 array([[1, 0],
        [2, 1]]))

In [53]:
# np.trace(Y) #even if python gives you something, it might not be correct!

In [54]:
# matrix inner product
np.trace(np.matmul(X, Z.T))

np.int64(8)

In [55]:
np.trace(np.matmul(Z, X.T))

np.int64(8)

In [56]:
# solutions to final practice
x = np.array([[2], [6]])
y = np.array([[1], [0]])
X = np.array([[7, 3],
              [-3, 6]])
Y = np.array([[-1, 1],
              [2, 0]])
Z = np.array([[4, -1, 0],
              [1, 1, 1]])

In [57]:
np.trace(np.dot(x, x.T)) + np.inner(x.flatten().T, y.flatten())

np.int64(42)

In [58]:
Y * X

array([[-7,  3],
       [-6,  0]])

In [59]:
2*X + X.T.dot(2*Y)

array([[-12,  20],
       [ 12,  18]])

In [60]:
np.trace(Y.dot(Y.T))

np.int64(6)

In [61]:
Y.dot(Y)

array([[ 3, -1],
       [-2,  2]])

In [62]:
np.matmul(Z, np.matmul(Z.T, y))

array([[17],
       [ 3]])