In [5]:
import numpy as np
import csv

# Open and read the CSV 
with open("hw1.csv", "r", encoding="utf-8-sig") as f:
    reader = csv.reader(f)
    data_list = [row for row in reader]

# Convert to NumPy array of floats
data = np.array(data_list, dtype = int)

# Print the data matrix
print(data)


[[ 4  8 15]
 [16 23 42]
 [ 6 13 18]
 [16 15 32]
 [16  9 38]
 [11 19 16]
 [11  9 24]
 [15 14 19]
 [ 0  6 44]
 [16  7 46]]
