In [1]:
# This code shows how to read external data (csv in this case) and
# add the bias column using numpy
import pandas as pd
import numpy as np

# 1. Read the CSV file
df = pd.read_csv("data.csv")   # assumes your CSV has a column "x"

# 2. Extract the feature column as a NumPy array (shape = (n,1))
X = df[["x"]].values

# 3. Add a bias (intercept) column of ones
phi = np.hstack([X, np.ones((X.shape[0], 1))])

print("Original data:\n", df)
print("\nFeature array with bias (phi):\n", phi)


Original data:
    x
0  1
1  2
2  3
3  4
4  5

Feature array with bias (phi):
 [[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]]


In [2]:
# The same but now reading a x array from which we need to create
# feature matrix where the features are: x^2, x and the bias

import pandas as pd
import numpy as np

# 1. Read the CSV
df = pd.read_csv("x.csv")   # assumes the file has one column: "x"

# 2. Extract values into a NumPy array
X = df[["x"]].values   # shape (n,1)

# 3. Build the polynomial feature matrix:
#    - First column: x^2
#    - Second column: x
#    - Third column: bias (ones)
phi = np.hstack([
    X**2,
    X,
    np.ones((X.shape[0], 1))
])

print("Original X:\n", X)
print("\nFeature matrix phi:\n", phi)


Original X:
 [[0]
 [1]
 [2]
 [3]
 [4]]

Feature matrix phi:
 [[ 0.  0.  1.]
 [ 1.  1.  1.]
 [ 4.  2.  1.]
 [ 9.  3.  1.]
 [16.  4.  1.]]
